### ISSUE TITLE
Confirmed Cases Map Legend Level Change 

### ISSUE THREAD

**Issue by petronav** [covid19india/covid19india.github.io#1004]
**Is your feature request related to a problem? Please describe.**
Right now in the mini map of India where the total confirmed cases are shown, the legend levels is dynamically and linearly clustered wrt the highest total confirmed case for any state and thus no matter what, there will be only one state, the one with the highest confirmed cases will be shown the darkest red zone. At a point Maharastra had 1761 cases while Delhi had 1069 cases. The highest level of the map legend was 1760+. The highest red zone cut off is set by lowest multiple of 5 not exceeding the highest confirmed case among all states and the rest of the level range is decided by dividing this cut off by 5 and having multiple of that. Right now Maharastra has 1895 confirmed cases and the highest level of the legend is 1895+. Why decide the last legend range according to highest confirmed cases in such a way that possibly almost always only one state is shown as the darkest red zone?

**Describe the solution you'd like**
Wouldn't it be better if we have levels linearly like 0-250, 250-500, 500-750, 750-1000, 1000-1250, 1250+. The process could be to determine the highest total confirmed case X. Divide it by 6. Take the least multiple of 25 greater than this float. Make ranges wrt this integer. An example could be as follows : 
Highest Case = 1895.
Lowest Case = 1
Difference = 1894
Div = 1894/6 = 315.67
Ceiling integer, a multiple of 25 = 325
Ranges are = 0-325, 325-650, 650-975, 975-1300, 1300-1625, 1625+ [or maybe cluster according to the lowest case (case if it is 719) as there might not be any state in 0-325 range].
That way in hypothetical cases with second and third states having confirmed cases neck to neck with first state won't be left out of the darkest red zone.

**Describe alternatives you've considered**
Another process could be to introduce a continuous single colour temperature bar legend without any distinct ramp. 

**Additional context**
This same logic could be applied for all the state for their corresponding district wise views too.

**Comment by shuklaayush** [comment]
@petronav Hi! Thanks for the issue. I've also been thinking about this a lot. I experimented with a continuous legend in #865. What I realized was that it makes it even harder to perceive the value that the colour corresponds to in the legend, especially when differences are subtle.  Another way is to use a [quantile scale](https://gisgeography.com/choropleth-maps-data-classification/), but since it's non-linear, it might be misleading at first glance. 

The method that you've mentioned is also good but I couldn't find a way to implement it elegantly, especially since the numbers are always increasing.
