### ISSUE TITLE
Total Number of tests

### ISSUE THREAD

**Issue by akumar90** [covid19india/covid19india.github.io#1013]
Steps to Reproduce
* When user first navigates to the page, data for all the states is summed and displayed.
* Total number of tests is not displayed

![Screen Shot 2020-04-12 at 10 15 03 AM](https://user-images.githubusercontent.com/13646657/79075270-b1587080-7ca6-11ea-88e7-a91c5129eb60.png)

**Comment by sudevschiz** [comment]
Yes, this would be a valid expectation from the user. We can use the data released by ICMR to show this information. This is available in the data.json api too. 

Marking this available.

**Comment by SensehacK** [comment]
@sudevschiz Do you mind If I look into this issue. 
This would be first time having hands-on with react though on a live website but as long as I get it up and running on local machine. I'm good to go.

**Comment by SensehacK** [comment]
@sudevschiz 
I noticed one thing in the API's google sheet document source that sheet "Statewise" we don't have a column for Tested for each state & therefore we don't have cumulative tested number within the whole India.
Can we have that column added in the sheets document so that we can parse that number directly rather than calculating other states array every time with  a new request? 

![Screen Shot 2020-04-12 at 3 08 50 PM](https://user-images.githubusercontent.com/8469205/79077410-87677400-7ccf-11ea-9158-37fb786bd46d.png)

We can have Google Sheet API do the heavy lifting of crunching numbers within the sheet.
