### ISSUE TITLE
Footer Improvement

### ISSUE THREAD

**Issue by Abhinaay** [covid19india/covid19india.github.io#1039]
The footer looks uneven and asymmetric. It can be designed in a better way.

It will be a great pleasure for me if I could design it in a better way. I will use the design concepts and will try to create a better look and feel.

A motivating image or slogan can be further added in the footer if design requirements are being satisfied.

**Comment by sudevschiz** [comment]
This has already been worked on once before. However, rather than the misalignments, the footer buttons are now intuitive for the user and doesn't look like a standard social media icon footer. 
Let's just keep it that way. 

https://github.com/covid19india/covid19india-react/issues/1001
https://github.com/covid19india/covid19india-react/pull/1059

https://github.com/covid19india/covid19india-react/issues/686
https://github.com/covid19india/covid19india-react/issues/686
