### ISSUE TITLE
India's stats against other most infected countries from the days since 100th infection,

### ISSUE THREAD

**Issue by mehuled** [covid19india/covid19india.github.io#1150]
**Is your feature request related to a problem? Please describe.**
- I would like to see how is India responding to the worldwide pandemic, just knowing numbers without an external reference scale makes it difficult to asses how better/worse we are doing than the others.

Pandemic is global and we must see if we are going in the right direction.

**Describe the solution you'd like**
I would like to work on a line graph that displays the Number of actives cases vs No. of days since the 100th infection graph for India and other top infected countries.

**Describe alternatives you've considered**
I myself prepared a graph using chart.js to asses India's situation as compared to the world. 
Other sites like worldometer do have the numbers for all the countries but a graph would only make it more insightful.

**Additional context**
https://twitter.com/ianbremmer/status/1245448348372361217?s=09

**Comment by Code5500** [comment]
Can be done but woukd take a lot of statistical data .

**Comment by animesh-tarodia-sp** [comment]
we can make use of pomber api for the data.
link:-  https://github.com/pomber/covid19

**Comment by drdebmath** [comment]
If you are looking for a visualization, you can find it at http://91-divoc.com/pages/covid-visualization/
It would be helpful to have such a visualization for state-wise cases to show the growth in one state vs the other, which may help in assessing the effectiveness of containment measures.

**Comment by mehuled** [comment]
Yes, @anitarodia exactly what I used to create my own visualization.

@drdebmath Yes agreed that makes sense too, but we already have that on the website.

I would still like to wait for a moderator to consider the feature request.

**Comment by sudevschiz** [comment]
This could be a graph in deep-dive section. Please do discuss where you'll get the right data for other countries and how it would look like (a simple mockup?)

**Comment by saurabhsharma1976** [comment]
https://www.worldometers.info/coronavirus/  offers the best tabular data.
I suggest we pull from there. Have contacts in other countries incl Wuhan
and this is verifiable - of course like China countries can underdeclare...

------------------------------
*From:* Sudev <notifications@github.com>
*Sent:* Sunday, April 19, 2020 6:34:13 AM
*To:* covid19india/covid19india-react <covid19india-react@noreply.github.com
>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Subject:* Re: [covid19india/covid19india-react] India's stats against
other most infected countries from the days since 100th infection, (#1150)


This could be a graph in deep-dive section. Please do discuss where you'll
get the right data for other countries and how it would look like (a simple
mockup?)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/covid19india/covid19india-react/issues/1150#issuecomment-615998307>,
or unsubscribe

**Comment by jeremyphilemon** [comment]
Hey thanks for filing the issue, unfortunately we're gonna have to mark this as abandoned since the feature addition in question is either out of scope or that we simply don't have enough data to support said feature. 

Feel free to open an issue in the future if you think otherwise :)
