### ISSUE TITLE
Timeseries stats overlap with graph

### ISSUE THREAD

**Issue by ravigaggad** [covid19india/covid19india.github.io#1222]
**Describe the bug**
Graph of confirmed patient and number of Patient overlap and number is not visible
**To Reproduce**

1. Go to  covid 19 website
2. Scroll Down to Spread Trends
3. Click on cumulative Graph
4. Select a Kerala State option from List box.
5. Click on two week button.
6. Drag the finger on confirmed patient graph.
7. Observers the Number of patient is overlapping with graph

**Expected behavior**
Graph of Confirmed patient overlap with numbers of patients
![IMG_20200417_195829](https://user-images.githubusercontent.com/63439607/79579921-dd7c5300-80e5-11ea-9bfe-73584dffb10b.JPG)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by strikertanmay** [comment]
I would like to work on this. Please assign me

**Comment by jeremyphilemon** [comment]
@strikertanmay hey, thanks for requesting to work on it :)

How are you planning to go about the fix?

**Comment by strikertanmay** [comment]
@jeremyphilemon By giving some left padding fix this problem very well. Attached SS after applying padding. If all things look fine to you. Can I make PR for this? :)
![Screenshot from 2020-04-18 17-14-13](https://user-images.githubusercontent.com/32292953/79636948-06a9eb80-8199-11ea-967b-5b86e068d60f.png)

![Screenshot from 2020-04-18 17-15-49](https://user-images.githubusercontent.com/32292953/79636941-ff82dd80-8198-11ea-8a3a-d8bcc824a240.png)

**Comment by nsjithin** [comment]
Also in small screens, the stats area prevents the user to click on the very top-left points in the graph as the stats area overlaps it. 

1. Adding a left padding for the graph is an option, but it has to left pad more to fix the overlapping issue and there will be more wasted blank space in the small screens. OR can left pad with minimal content so that there won't be much wasted space.

OR

2. Display the minimal stats text on the top or bottom of the graph and place graph accordingly so that the text won't affect the graph.

OR

3. Display the stats in a tooltip/popover in small screens so it will be placed accordingly. 

Thoughts?

**Comment by strikertanmay** [comment]
@nsjithin U are right. As we can see the stats are already minimal and I don't think there is a point to minimalize the content just to fix the UI bug.
On point (1), I would like to say only a minimal amount of padding can fix this issue. I checked on different media screen sizes no such blank space wasted and UI looks cleaner and good.
That's why as an example I attach SS of the screen size (375 * 812) which is very smaller.

**Comment by strikertanmay** [comment]
@nsjithin https://covid19india-react-cv8k071nf.now.sh, please view this and if you really think changes are required then we will discuss what we can do next. Thanks :)

**Comment by nsjithin** [comment]
Please select state Kerala and 2 Weeks filter from bottom and try to click on the first point in the graph. The stats area prevents the click as the stat area div is over the point. 

This issue will start to appear more when the curve gets flatten. Now the data is in increasing phase so there will be room over the top left of the graph, but when the curve gets flattened the left/first points in the graph will be more top aligned and the stats area will overlap it.

**Comment by strikertanmay** [comment]
> Please select state Kerala and 2 Weeks filter from bottom and try to click on the first point in the graph. The stats area prevents the click as the stat area div is over the point.
> 
> This issue will start to appear more when the curve gets flatten. Now the data is in increasing phase so there will be room over the top left of the graph, but when the curve gets flattened the left/first points in the graph will be more top aligned and the stats area will overlap it.

I can understand your concern. Sorry but I don't face any problem while clicking over the first point. And I am saying that because of padding if the stats area div is outside the graph axis then how it can prevents the click or overlap the content ?

**Comment by jeremyphilemon** [comment]
@strikertanmay Instead of applying the left padding, can we show "Yesterday" on the right of the graph instead?

**Comment by strikertanmay** [comment]
> @strikertanmay Instead of applying the left padding, can we show "Yesterday" on the right of the graph instead?

By considering your given option there will be chances that it can overlap with "confirmed" or with dates. That's why I think padding is the best and safest option.
Please tell if I'm wrong or you have any more approach

**Comment by jeremyphilemon** [comment]
@strikertanmay, I [patched](https://github.com/covid19india/covid19india-react/commit/e70b495110c17fb4fe5ccd106d6677c40d568c9el) the issue by moving them to the right, also addressing @nsjithin 's concerns.

We needed to introduce changes to the testing graph, hence I had to hijack this issue, I hope you understand :)
