### ISSUE TITLE
Mumbai Suburban showing 0 cases while its a most affected district.

### ISSUE THREAD

**Issue by tshrwbl** [covid19india/covid19india.github.io#1287]
**Describe the bug**
Even though most of the cases from Mumbai are in Mumbai Suburban district, The data displays all cases in Mumbai city district.
![image](https://user-images.githubusercontent.com/27141947/79683821-3bc24680-824a-11ea-8550-91b834f8c533.png)

**To Reproduce**
Click on Mumbai Suburban district and Mumbai City district.

**Expected behaviour**
It's a tricky part. How do we count cases of Mumbai? Do we have a district-wise number from the government? News sources label even Navi Mumbai cases as a "New cases in Mumbai" while they are technically outside of both districts of Mumbai. (Navi Mumbai is a part of Thane and Raigad dist.)
Is there any way to confirm if data is accurate district-wise?

**Comment by jeremyphilemon** [comment]
cc @bee-rickey

**Comment by tshrwbl** [comment]
Any lead on this?

**Comment by sgandhi9** [comment]
I think we should merge Mumbai and Mumbai Suburban districts. The data from Brihanmumbai Municipality Corporation (Local municipality body) also release data as one for daily cases.

Just for reference: 
https://twitter.com/mybmc/status/1257706125530525703?s=20

**Comment by bee-rickey** [comment]
I don't think we can fix this. The reason is two fold -
1. We can't go based on bmc bulletins. We follow state bulletins and it become impossible to reconcile data given by districts with states as their time frames for reporting are different.
2. Merging two geographical districts is not a call we can take. I'm not even sure if it's legal to do so :P. If we remove Mumbai Suburban and keep it as Mumbai on the map, it pretty much means we do not acknowledge the existence of Suburban :D

I'll close this issue for now. Please tag me in the comments if you feel otherwise.

**Comment by sank8dalvi** [comment]
This issue can be solved by considering Mumbai Suburban and Mumbai as one district and they are also referred as one district by Maharashtra government.
I can fix the map by editing the topojson as I have experience working with it.
I will remove Mumbai Suburban completely which as of now is shown as zero cases and expand Mumbai to cover Mumbai Suburban as well.
I will be editing maharashtra.json using this website.
http://geojson.io/
Since I have worked with Topojson I would like to /claim this issue
@bee-rickey
