### ISSUE TITLE
Network of Transmission - Additions

### ISSUE THREAD

**Issue by TheDominus** [covid19india/covid19india.github.io#1314]
**Is your feature request related to a problem? Please describe.**
**Show Patient Info** 
See the patient information via a small popup on clicking/hovering on the dot. 
**Add details about missing information**
Add a link to google doc asking people for more information about the transmission graph via regional sources. 
**Add more colors for distinctions**
Color1 - Travelled from other state with disease
Color2 - Passed the infection to other person
Color3 - infected but did not pass the disease
**Full-Screen Mode**
Add a  detailed analysis window by opening the network in new tab/making this info in full screen for a network of transmission
**Data is not completely available for some states** [BUG]
There are only 2 dots for Jharkhand state

**Comment by gyanendrapatro** [comment]
you can assign this to me

**Comment by gyanendrapatro** [comment]
@shuklaayush could you tell about this point Add details about missing information
Add a link to google doc asking people for more information about the transmission graph via regional sources.( do you have any link which we can put there).

Data is not completely available for some states [BUG]
There are only 2 dots for Jharkhand state( this is checked the information is not there like transmitted from whom thats y its not coming in the graph)
so the plan is we can just plce those dots without any link as information is not that and when user clicks on it the popup will come showing user info like patent id, place and all and the link of the form where the users can fill the details so that next time it will get linked with some patient

**Comment by gyanendrapatro** [comment]
Add more colors for distinctions
Color1 - Travelled from other state with disease
Color2 - Passed the infection to other person
Color3 - infected but did not pass the disease

if scenario 1 and 2 are there then how we will put color its difficult to assign color if the patient travleed from outside and also passed the infection.

**Comment by TheDominus** [comment]
"if scenario 1 and 2 are there then how we will put color its difficult to assign color if the patient travleed from outside and also passed the infection."
In this case, you  can assign a separate color may be a color which is a combination of 2 like orange = red  + yellow

**Comment by TheDominus** [comment]
@gyanendrapatro, I hope you are working on this issue. I want this feature to be live on website. Do ask for help from others if you need anything. or if you don't have bandwidth ask anyone else to continue working on this issue.

@shuklaayush, Can you provide the assigned person the link of google form/database entry point where you maintain the travel details of patients or contact tracing details.

With more migrants people coming from other states, we will need this data/graph help many for contact tracing.

Thanks @gyanendrapatro @shuklaayush for making this project successful.

**Comment by shuklaayush** [comment]
@TheDominus I think this data is rarely being released by the state governments ever since the volume of cases has increased. Also, the transmission network is based on data taken from raw_data.json API which has since been frozen. I don't have time right now to add/replace the API and/or check if the data is being updated, but on the face of it, there seems to be a significant possibility that we might have to deprecate this feature.

> @shuklaayush, Can you provide the assigned person the link of google form/database entry point where you maintain the travel details of patients or contact tracing details.

@sudevschiz might be able to help out here

**Comment by sudevschiz** [comment]
Except for very few states (only KA maybe), the information about from who the patient contracted the virus is not shared anymore. I sincerely hope that the government is still doing contact tracing actively. However, with the large number of cases that are getting added everyday,   reality could be harsher. 

Anyway, this data is not sufficiently available and the network transmission graphs that are present in the website is quite outdated and as @shuklaayush mentioned, could be deprecated soon. Closing this feature request.
