### ISSUE TITLE
Confirmed cases number incorrect for multiple districts of Karnataka

### ISSUE THREAD

**Issue by vivekvroy** [covid19india/covid19india.github.io#1325]
![image](https://user-images.githubusercontent.com/10249914/79721931-cf564e80-8300-11ea-809a-9a123bb11ade.png)

Many districts numbers are incorrect.
Data taken from [https://covid19.karnataka.gov.in/storage/pdf-files/Media-Bulletin/19-04-2020-05-00-English.pdf](url)

**Comment by bee-rickey** [comment]
This is under discussion. The issue is with Karnataka govt changing their counting logic on 14th April. Check the notes in this [bulletin](https://karunadu.karnataka.gov.in/hfw/kannada/nCovDocs/14-04-2020(English).pdf). This is a weird way of counting cases for districts. 

<img width="721" alt="image" src="https://user-images.githubusercontent.com/63364562/79798532-c902b980-8376-11ea-8a99-295a882c2c5a.png">

13th April:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/63364562/79798804-20a12500-8377-11ea-916c-c714afdddce6.png">

14th April:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/63364562/79798838-2bf45080-8377-11ea-816f-58b54cdc01fc.png">

**Comment by jeremyphilemon** [comment]
Please report data discrepancies in this form https://forms.gle/7NRSrbspW2a6pbm58, thanks :)
