### ISSUE TITLE
Feature Requests and Enhancements required

### ISSUE THREAD

**Issue by danielsingh** [covid19india/covid19india.github.io#15]
a few suggestions:

- [ ] Home page has tons of free/empty space in the center and any possibility to make it in 1 Page and a bit tight and clean.
- [ ] Top Menu to be alternative colors so its more visible
- [ ] From Network Map page there is no navigation button to get back to home, it looks like we have moved to a diff site.
- [ ] Unable to export the zoomed in images of the cluster
- [ ] Please provide alternative view to the cluster, eg: tree, etc
- [ ] Helpful links could be accommodated in the home page itself saving 3 page need.

**Comment by Abijeet** [comment]
Thanks for the website. Its a very useful utility as is, but since you guys are actively working on improving it, here are a few more things to consider,

1. Unnecessary scrollbar on 1440x900, Firefox - ![image](https://user-images.githubusercontent.com/1685517/77280916-acc61b00-6ceb-11ea-8794-7da79eee1743.png) Whereas, on a larger resolution, there is lot of space in the center - 
![image](https://user-images.githubusercontent.com/1685517/77281623-7f7a6c80-6ced-11ea-9c59-6f7f58c61ab9.png)

2. Network map does not seem to have its own route, making it difficult to paste a link to it directly.
3. We now have **Last Reported Case**, but there is a chance that there have been no changes for a while but you guys still monitor and keep things upto date. I think we should have a **Last reviewed on** or something like that.
4. Ensure all numbers are right aligned.

**Comment by jeremyphilemon** [comment]
@JunaidBabu @sudevschiz Thoughts on the "Last Reported" heading?

**Comment by JunaidBabu** [comment]
> #### Last Reported
> @JunaidBabu @sudevschiz Thoughts on the "Last Reported" heading?
> 

Change to "Last updated xx minutes ago"

**Comment by sudevschiz** [comment]
@JunaidBabu There is an another issue that timestamp should be absolute. Let's change to that because screenshots of the website is being shared in Whatsapp etc. and an absolute timestamp would be better in that case.

"24 March 2020 10:43 PM IST" 
What do you think?

**Comment by sudevschiz** [comment]
@sibeshkar  Could you have a look at the suggestions regarding the cluster map

**Comment by jeremyphilemon** [comment]
> Home page has tons of free/empty space in the center and any possibility to make it in 1 Page and a bit tight and clean.

We'd like it to be that way, less clutter and more information

>  Top Menu to be alternative colors so its more visible

It's more visible now since the addition of the banner

> From Network Map page there is no navigation button to get back to home, it looks like we have moved to a diff site.

Fixed!

 > Unable to export the zoomed in images of the cluster, Please provide alternative view to the cluster, eg: tree, etc

Please direct issues about the cluster to https://github.com/covid19india/covid19india-network

> Helpful links could be accommodated in the home page itself saving 3 page need.

We feel it's better to have the helpful link as a separate page

Thanks!
