### ISSUE TITLE
Access database issue it frozen (#1359)

### ISSUE THREAD

**Issue by aamir200** [covid19india/covid19india.github.io#1518]
issue #1359 is not solved and you guys are closed the ticket may I know why?

1st check this site is updating the data or not and then tell others
Duplicate of # http://patientdb.covid19india.org/

**Comment by bee-rickey** [comment]
Hi @aamir200 the APIs are working fine. We have discontinued the patientdb since it's too heavy to load and doesn't add much benefit. Please use the APIs listed at [api.covid19india.org](https://api.covid19india.org/) All of them are functional and updated.

Note: We are making some changes to raw_data apis and would request you to not use it until we are done with the changes (you can refer to the api.covid19india.org, we will update the changes there once they are complete).
