### ISSUE TITLE
Tree-shake primer components

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#1648]
**Is your feature request related to a problem? Please describe.**
The primer components are imported as a whole and is bloating the bundle size. 

**Describe the solution you'd like**
Tree shake the imports as mentioned here: https://primer-components-bkeydftbnx.now.sh/components/docs/getting-started

**Additional context**
The primer components (breadcrumb and dropdown) are used in the state pages.

**Comment by jeremyphilemon** [comment]
I'm leaving this open for first-time contributors, so please be mindful before claiming :)

/available

**Comment by jeremyphilemon** [comment]
@nitkuk Hey were you able to make progress wrt this issue, I shall open it up again if otherwise :)

**Comment by niinpatel** [comment]
Hey @jeremyphilemon, can I take up this issue?

**Comment by jeremyphilemon** [comment]
@niinpatel Sure go ahead :)

**Comment by niinpatel** [comment]
Actually, it seems that we cannot just import individual modules into our app right now, `import Dropdown from '@primer/components/src/Dropdown'` does not work because primer does not export the transpiled jsx. 

This will be fixed in v19.0.0 according to this -> https://github.com/primer/components/issues/797

It seems that we're using create-react-app so it doesn't transpile the third party packages imported from node_modules, so we'll either have to eject our app to configure webpack or wait for v19.0.0 of primer to be released.
 
I think we should just do the latter.

**Comment by shubhamjain2998** [comment]
what if we implement dropdown from material ui component library and remove primer completely @jeremyphilemon .

**Comment by niinpatel** [comment]
> what if we implement dropdown from material ui component library and remove primer completely @jeremyphilemon .

That's a good idea. I'll see if the components we're importing from primer are there in material-ui and see how it looks if we use those instead.

**Comment by BinaryMuse** [comment]
Primer Components `v19.0.0` is available and should have what you're looking for; if you're not using ESM, you can import components from the `lib/` folder. See https://primer.style/components/getting-started for more info.

**Comment by niinpatel** [comment]
> Primer Components `v19.0.0` is available and should have what you're looking for; if you're not using ESM, you can import components from the `lib/` folder. See https://primer.style/components/getting-started for more info.

Thanks for letting me know @BinaryMuse. 

@jeremyphilemon I've raised a PR, can you check. :)
