### ISSUE TITLE
Showing negative data in 'tested' graph

### ISSUE THREAD

**Issue by parthbhide** [covid19india/covid19india.github.io#1723]
**Describe the bug**
Tested graph under when plotted as "daily" is showing negative numbers . How can a state test negative number of people ? Probably it is because the difference b/w yesterday's and today's value is plotted rather than today's value.

**To Reproduce**

1. Go to covid 19 home page
2. Scroll down to the graph section , select state "Madhya Pradesh" and plot as "Daily"
4. See error in "Tested" graph

**Expected behavior**
Plot daily value rather than the difference.

**Screenshots**
![Screenshot_2020-05-02-20-48-40-361_com android chrome](https://user-images.githubusercontent.com/50196988/80868350-a7c79480-8cb7-11ea-85e7-db4b13c5c130.jpg)

**Comment by parthbhide** [comment]
I can contribute to this if accepted.

**Comment by shuklaayush** [comment]
This is based on the daily testing data released by the MP state bulletin. Tagging other people who might be able to elaborate further.
/cc @bee-rickey @sudevschiz

**Comment by shubhamjain2998** [comment]
@shuklaayush I think that this issue is because the calculation of current calculation of daily testing numbers for a particular day is done by subtracting total tests done that day and previous day testing, so generally the trend is everyday testing numbers increase only, so the difference will always be positive. But if in case there is less testing done the next day then the resulting value will be negative and that's the case above. Daily tests should be absolute numbers.

See the cumulative graph screenshot and then see the ss in question, you will get my point.

![Screenshot from 2020-05-02 22-56-49](https://user-images.githubusercontent.com/30628775/80871330-92f3fc80-8cc9-11ea-9558-44aeec4391a3.png)
![Screenshot from 2020-05-02 23-07-00](https://user-images.githubusercontent.com/30628775/80871353-b0c16180-8cc9-11ea-9c95-bf8d087a87f1.png)

Same graph after making absolute subtraction here.
https://github.com/covid19india/covid19india-react/blob/9d58688b4a80f955cb679f6504a634a077c2605f/src/utils/commonfunctions.js#L169

![Screenshot from 2020-05-02 23-16-39](https://user-images.githubusercontent.com/30628775/80871592-16fab400-8ccb-11ea-8ec8-b4df7513dfe5.png)

**Comment by parthbhide** [comment]
@shuklaayush @shubhamjain2998 . The problem is in API itself. Please have a look at data below for date 20/04/2020 and 21/04/2020 . Total tested on 20/04/2020 are 27661 and that on 21/04/2020 are 20905 according to covid19 API.  

![image](https://user-images.githubusercontent.com/50196988/80871907-3e9e4c00-8ccc-11ea-907e-c15b103060f8.png)

Going through the references therewith we may observe that Total tested on 20/04/2020 are 27661 and that on 21/04/2020 are 29120. I am attaching all the references below. Please look into it and do the necessary changes.

**20/04/2020** :
https://twitter.com/JansamparkMP/status/1252220621112647683/photo/2

![image](https://user-images.githubusercontent.com/50196988/80871965-9fc61f80-8ccc-11ea-8ba8-99d941127c7f.png)

**21/04/2020**
https://twitter.com/JansamparkMP/status/1252572205768114178/photo/1 

![image](https://user-images.githubusercontent.com/50196988/80871975-ad7ba500-8ccc-11ea-83f2-72607c22fe22.png)

**Comment by bee-rickey** [comment]
@parthbhide The issue on 13th April is something that cannot be corrected due to the issue with data given by the state report. Wrt, 20-21st, I'll get back to you. Figuring out why the total samples collected was used just for 21st.

**Comment by shubhamjain2998** [comment]
Ohh I see there is a discrepancy in API too, I don't know much about the API part but still feel the above-suggested fix is needed, in case if there is any low number of tests done.

**Comment by parthbhide** [comment]
@bee-rickey .. thank you for your kind attention. From 21st onward till 25th we are using "total samples collected" . From 26th format of report changed ( hence you may see the same above mentioned issue ). This probably made data more ambiguous.


**25-Apr**
![image](https://user-images.githubusercontent.com/50196988/80885479-313c8e00-8cdb-11ea-9021-04bd56ad5b92.png)

**26-Apr**
![image](https://user-images.githubusercontent.com/50196988/80885759-46192180-8cdb-11ea-9d86-de738702d4a9.png)

**Comment by parthbhide** [comment]
probably the issue is with state data itself .. you may close if not necessary.

**Comment by shuklaayush** [comment]
@shubhamjain2998  The 'totaltested' variable coming from the API is the total tests conducted **till** (and including) that date. It is not the tests conducted **on** that date. Hence, it should ideally be a monotonically increasing series. Taking the absolute value has no logical basis. I don't think we can do anything about this unless there's a clarification from the government.

**Comment by shubhamjain2998** [comment]
@shuklaayush sorry my bad, I just got totally confused in daily and total calculation. You can close this issue now.
