### ISSUE TITLE
In telangana state, in district column,in unknown a error in the no. of cases.

### ISSUE THREAD

**Issue by jatin0406** [covid19india/covid19india.github.io#1770]
summation of the number of recovered and decreased cases is equal to 195 but confirmed cases are just 29.
![error](https://user-images.githubusercontent.com/42699221/80971448-6a3f4480-8e3a-11ea-937a-4a52f1d24cf3.png)

**Expected behavior**
when you open the site and open the location you see just as described in the screenshot and above context.

**Screenshots**
![error](https://user-images.githubusercontent.com/42699221/80971646-b5f1ee00-8e3a-11ea-989d-39a0f5bdce74.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] windows
- Browser [e.g. chrome, safari] microsoft edge

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] note 5 pro
- OS: [e.g. iOS8.1] oreo 8.1.0
- Browser [e.g. stock browser, safari] chrome

**Comment by bee-rickey** [comment]
The understanding of unknown row:
Unknown confirmed: "x" cases out of total state cases are not mapped to a district.
Unknown recoveries: "y" recoveries out of total state recoveries are not mapped to a district.
Unknown deceased: "z" deceased out of total state deceased are not mapped to a district.

These numbers are independent of each other and are those cases that we've not been able to map to a district due to state data being insufficient.
