### ISSUE TITLE
Breakdown by District don’t show recovered.

### ISSUE THREAD

**Issue by pradeepbheron** [covid19india/covid19india.github.io#185]
![3FD1A2D9-9C92-4136-BCA8-105FAAD39D67](https://user-images.githubusercontent.com/840782/77656700-431f6880-6f9a-11ea-9da9-081ff01ffde0.jpeg)
**Describe the bug**
I’m on iPhone 7 + safari browser 

Breakdown by district didn’t show recovered cases, attached screenshot. I’ve drilled Haryana state and expecting 11 recovered in Haryana. I know those were foreigners but when we count them in total then we should count them in recovered too.

**Comment by pradeepbheron** [comment]
Also same for Active cases, that’s showing same as total cases, doesn't match with total numbers in Active cases. As per screenshot Active should show 21.

**Comment by sudevschiz** [comment]
@pradeepbheron Thanks for reporting this bug. 

@jeremyphilemon @JunaidBabu , currently, we cannot calculate the Recovered, Deceased, Active numbers at a district level because, many states doesn't release the data at that granularity. It's simply not feasible to show that information.

Only confirmed numbers can be shown. What do you think about the following representation?

![image](https://user-images.githubusercontent.com/4298868/77661852-84c20a80-6fbe-11ea-853a-23f24307998a.png)

**Comment by roh-kan** [comment]
There is some issue with the calculation of "Recovered" state wise e.g. 
As per sheet, UP - 2 Recovered, 42 Hospitalized.

In the table, its 11 Recovered, 42 Hopitalized
<img width="495" alt="image" src="https://user-images.githubusercontent.com/2139429/77663530-1f6b1b00-6fb8-11ea-8c5d-4454f81ec804.png">

**Comment by JunaidBabu** [comment]
@jeremyphilemon 

https://api.covid19india.org/state_district_wise.json
I'll remove active, deaths and recovered from the above api once the modification is done on the site. 


"districtData": {
      "Thrissur": {
        ~~"active": 3,~~
        "confirmed": 5,
        ~~"deaths": 0,~~
        "lastupdatedtime": "",
        ~~"recovered": 2~~
      }

**Comment by JunaidBabu** [comment]
Fixed f1afbc1941f56f16ada6406bb7b55521bc86af86
