### ISSUE TITLE
Negative Recovered in West Bengal data

### ISSUE THREAD

**Issue by ayushag10004** [covid19india/covid19india.github.io#1897]
**Describe the bug**
I am seeing negative recovered in westbengal recovered graph on homepage
**To Reproduce**
always reproducible 

1. Go to homepage
2. Click on westbengal
3. See recovered graph on right side

**Expected behavior**
not getting the meaning of negative recovered 

**Screenshots**
<img width="562" alt="Screenshot 2020-05-16 at 12 04 58 AM" src="https://user-images.githubusercontent.com/35866910/82084415-e3774b00-9708-11ea-98ca-1f7ec2a0295f.png">
**Desktop (please complete the following information):**

**Comment by bee-rickey** [comment]
3rd May is when we shifted from MOHFW updates to state updates. Till the the state was not giving recovery numbers. Hence on that day there's a backward adjustment done and this resulted in the negative value. Nothing much can be done about this since this is an issue with state not releasing numbers in a timely manner.
