### ISSUE TITLE
Set "Last Updated" to a time stamp instead of "hours ago"

### ISSUE THREAD

**Issue by tecoholic** [covid19india/covid19india.github.io#2]
Setting a relative timestamp on images will make the image irrelevant as time progresses. In the worst case, might lead to confusion. Better to use a timestamp instead of saying "2 hours ago".

**Comment by jeremyphilemon** [comment]
Clarifying, which images are you talking about?

**Comment by sudevschiz** [comment]
Probably about this 
![image](https://user-images.githubusercontent.com/4298868/77434660-8c4dac00-6e24-11ea-9964-9357e18f98bc.png)


I agree with @tecoholic , but @triedcatched didn't wanted to do the calculation in his mind about how far in the past is the timestamp :P 
But I vote for timestamp with timezone (IST) be present because people are sharing the home screen's screenshot in Whatsapp as status etc. 

In that case, absolute time is necessary.

**Comment by JunaidBabu** [comment]
debatable... maybe run a poll in the ops group and decide

**Comment by jeremyphilemon** [comment]
Poll:

<img width="294" alt="Screen Shot 2020-03-28 at 1 58 36 AM" src="https://user-images.githubusercontent.com/17938322/77807056-a9d67c00-7097-11ea-9568-3042bd03edb3.png">
