### ISSUE TITLE
Incorrect Confirmed numbers reflecting on Portal

### ISSUE THREAD

**Issue by ashishgujrathi** [covid19india/covid19india.github.io#2025]
**On 2nd Jun'20, till 6:05 PM IST**
**Total Confirmed Case - 1544
Active - 1293
Recovered - 244
Desceased - 7**

When person found to be infected with Covid-19 on X day, then count of person added in **active** and **confirm** case on X day itself but when same person **recovered or deceased** on Y day then that numbers too are adding in Y day **confirmed** numbers. So in this case for a person there is 2 entry - **one in active and other one in recovered/deceased.**
Due to which it getting confusion that today **1544** found to be **confirm** cases who have covid-19 but this figure include **recovered and deceased** too.
So to correct this, only **active** count should reflect in daily **confirmed** count field which is **highlighted in yellow** because person either **recovered or deceased** is already present in **confirmed** count.
It's simple that if person **recovered/deceased** would be from **Confirmed** numbers only

![Bug_02062020](https://user-images.githubusercontent.com/13534446/83525604-db8a1a00-a502-11ea-8aae-f30fae3273af.PNG)

**Comment by Manbendra** [comment]
I would say it is not an issue.
Total new cases in your image is 1544.
And today 244 people recovered and 7 lost their lives.
So total increase in active cases is 1544-244-7(new cases which came today - number of people whose outcome came)

**Comment by pankajtau** [comment]
At least FARIDABAD-HARYANA references are not being picked up correctely since atleast last 3 days.
perhaps nhmharyana is publishing 2reports and total sum is to be taken of both reports - also aymptomatics counting or not is not clear as that is also a large number - Govt authorities are trying to fudge data - if you lift daya from TWITTER HANDLE OF @DC_Faridabad- HUGE diff. with NHMharyana for last 3days data
![image](https://user-images.githubusercontent.com/65185180/83536922-86093980-a511-11ea-863f-388d098ce2c2.png)

[not tallying with DC FBD -Media Bulleitin 01-06-2020 Evening.pdf](https://github.com/covid19india/covid19india-react/files/4718046/not.tallying.with.DC.FBD.-Media.Bulleitin.01-06-2020.Evening.pdf)
![not tallying with DC FBD1jun-2jun -NHM](https://user-images.githubusercontent.com/65185180/83537280-f9ab4680-a511-11ea-9446-ad1e2180810b.jpg)

**Comment by ashishgujrathi** [comment]
@manbendra 244 were recovered and 7 deceased but this total 251 counts was earlier added in Confirmed when they found covid-19. So it's not required to add again this number in today's confirmed counts

**Comment by ashishgujrathi** [comment]
There is no need to add Recovered and death count in confirmed counts. As earlier these case was in Active status after it they transferred to recovered or deceased status. You can add-subtract active/recovered/death count.

**Comment by Manbendra** [comment]
@ashishgujrathi You are probably misreading the numbers. The total new cases today were 1544(probably you are thinking there are just 1293). Now Active cases number shows how many cases are active today(i.e. their outcome is yet to come).
So the active cases should have increased by 1544 today had there been no new recovered cases. But since few people recovered they are no more active that is why we are removing them from active cases.

**Comment by ashishgujrathi** [comment]
@Manbendra Iwant to say suppose if today I'm found to be affected from covid-19 then I will be count in today's active and confirmed number. Now if I'm recovered tomorrow then again I would be count in confirmed counts too.

**Comment by pankajtau** [comment]
@manbendra @ashish gujarati - i am trying to locate from where data
mismatch started and cheking other cities / state data also but I am not a
softer guy so what will be outcome dont know- but faridabad is a SURE
MISMATCH as in state data as well as in district compilation too.
[image: image.png]

**Comment by pankajtau** [comment]
@manbendra @ashish gujarati - i am trying to locate from where data mismatch started and cheking other cities / state data also but I am not a softer guy so what will be outcome dont know- but faridabad is a SURE MISMATCH as in state data as well as in district compilation too. shortfall of 73no. in cases - 
am already worried about how authorities fudging HOMEQUARINTINE & Asympto datas but this mismatch is to be corrected.
![image](https://user-images.githubusercontent.com/65185180/83595904-e5526280-a580-11ea-8d88-ac8e9518d433.png)

**Comment by ashishgujrathi** [comment]
@pankajtau Also we've to look into below figure and need to assign this case to states from unassigned due to which we don't know the exact figures of each states.

![image](https://user-images.githubusercontent.com/13534446/83610995-f1005200-a59d-11ea-9936-1f94035a6d95.png)

**Comment by bee-rickey** [comment]
> @pankajtau Also we've to look into below figure and need to assign this case to states from unassigned due to which we don't know the exact figures of each states.
> 
> ![image](https://user-images.githubusercontent.com/13534446/83610995-f1005200-a59d-11ea-9936-1f94035a6d95.png)

What's the significance of this in this conversation?

**Comment by bee-rickey** [comment]
> @Manbendra Iwant to say suppose if today I'm found to be affected from covid-19 then I will be count in today's active and confirmed number. Now if I'm recovered tomorrow then again I would be count in confirmed counts too.

Wrong understanding. The active "Delta" is the total number of new requirements that have come up today. This is the logic followed elsewhere to calculate the delta active. Now consider on a day you have "X" new cases, "Y" recoveries and "Z" deaths. In that case, for that day you'll free up "Y + Z" number of beds. Or in other terms, your load on medical system will go down by "Y + Z" number. Now on the same day the load on the system goes up by "X" number. Hence the active cases that get added on that day is "X - Y - Z". This is a per day calculation. You cannot consider the total active cases on a day to be same as the confirmed ones since people are getting discharged on that day. Hence you are reducing your active numbers.

**Comment by bee-rickey** [comment]
> At least FARIDABAD-HARYANA references are not being picked up correctely since atleast last 3 days.
> perhaps nhmharyana is publishing 2reports and total sum is to be taken of both reports - also aymptomatics counting or not is not clear as that is also a large number - Govt authorities are trying to fudge data - if you lift daya from TWITTER HANDLE OF @DC_Faridabad- HUGE diff. with NHMharyana for last 3days data
> ![image](https://user-images.githubusercontent.com/65185180/83536922-86093980-a511-11ea-863f-388d098ce2c2.png)
> 
> [not tallying with DC FBD -Media Bulleitin 01-06-2020 Evening.pdf](https://github.com/covid19india/covid19india-react/files/4718046/not.tallying.with.DC.FBD.-Media.Bulleitin.01-06-2020.Evening.pdf)
> ![not tallying with DC FBD1jun-2jun -NHM](https://user-images.githubusercontent.com/65185180/83537280-f9ab4680-a511-11ea-9446-ad1e2180810b.jpg)

Lets not mix up multiple things in one issue. We follow state bulletins for these numbers. Please refer to the state bulletins for understanding the discrepancy

**Comment by pankajtau** [comment]
ashish, you r very right here that unassigned cases r to be adjusted, but
that is mostly in SOUTH ESTATES i.e. AP, TN, KL etc .

here the point is that Decalred figures on local level must match with our
lifted data of the day.

**Comment by ashishgujrathi** [comment]
@pankajtau, Actually it's not only for SOUTH states. Same thing for **delhi** too where from last month numbers are getting added in **Unknown** district.

![image](https://user-images.githubusercontent.com/13534446/83634084-91b33980-a5bf-11ea-88ca-d3870b23491a.png)

**Comment by pankajtau** [comment]
i agree with you on this.

but our main issue of mismatch particular data still there
