### ISSUE TITLE
Calculations are wrong on total stats on top of the page and on the state table

### ISSUE THREAD

**Issue by supersid** [covid19india/covid19india.github.io#2038]
**Describe the bug**
The day-wise stat showing on the top of the page is not showing data correctly. According to me, the total number of Confirmed cases (for that particular day )should be equal to the total number cases active increased (for that particular day) and similarly, the total of recovered cases is also showing wrong.
All it is doing right now is splitting the increase of each day in confirmed cases into active, recovered and deceased. The same kind of behaviour is happening in the state-wise table.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
On the top where each day increase is shown it should come from the below state-wise table for all confirmed, active, recovered and deceased and in the state-wise table, the sum of active + recovered +deceased is equal to confirmed which should not be the case.
**Screenshots**
![Covid19PageError](https://user-images.githubusercontent.com/31355080/83595905-e5526280-a580-11ea-9345-8e91e5932ec2.jpeg)
In this photo, the underlined value is the issue
total confirmed cases each day = total active cases of each day + total recovered cases for each day + total deceased cases for each day.
this calculation is wrong.
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: iPhone X
- OS: OS 13.4.1
- Browser Safari

**Additional context**

**Comment by shuklaayush** [comment]
Let me try to make the calculation clear. There are essentially three independent metrics that we track:

1. **Confirmed cases (C)**: The total number of people to date who have tested positive for COVID-19.
2. **Recovered cases (R)**: Out of the total confirmed cases, the number of people who have recovered from COVID-19.
3. **Deceased cases (D)**: Out of the total confirmed cases, the number of people who have died due to COVID-19.

Using the values of these three metrics, we arrive at a new metric:

4. **Active cases (A)**: The total number of people who have COVID-19 right now. 
To calculate this, we subtract the recovered and the deceased count from the total confirmed cases i.e. _A = C - R - D_. 

Further, these definitions are also extended to calculate daily counts (deltas). What these represent are the change in the total counts for that particular day
i.e. _ΔA = ΔC - ΔR - ΔD_

These are not concocted definitions, but rather the standard way how such data is reported. I hope that clears things up.

**Comment by supersid** [comment]
Hi Ayush
I got your point and it makes sense. But I would like to discuss this further. Is there any way I can reach you out personally?

**Comment by shuklaayush** [comment]
Just write it here. The discussion might be useful for someone else who might be having the same doubts :)

**Comment by SarthakJain26** [comment]
shuklaayush I got your point, but what can a user understand by seeing the negative active cases! the first thing that comes to mind is "ok so on 16th of May there were -466 active cases in TN".

Having negative of active cases is like more people have recovered or died from the disease than people affected from the disease. This makes no sense

I don't think this should be the way to calculate the day wise active cases.

The correct formula to measure the delta should be:
change_in_active_cases =  active_cases_on_day_i - active_cases_on_day_i-1
And I have already mentioned the formula to caluclate the daily active cases in my issue

**Comment by shuklaayush** [comment]
You're confusing the definitions. The active cases are not negative. Only the daily (delta) active is negative.

> "ok so on 16th of May there were -466 active cases in TN"

That's not the correct way to read this graph. If you just want to see the number of active cases in TN on 16th May, just look at the cumulative graph, not the daily one. The way to interpret the daily graph is rather: "_On 16th May, the active cases in Tamil Nadu decreased by 466_".
