### ISSUE TITLE
Minigraph is misleading as it is not an acute representation of the trends.

### ISSUE THREAD

**Issue by zenquiorra** [covid19india/covid19india.github.io#2095]
The minigraph shown on the page is misleading since it shows a change in the number of active cases (or any other parameter), but the slope of the graph at that point should depend on the total number of people tested.
If the motive of minigraph is to show trends, then the current metrics are not the true representation of the trends and just show the change in data from the previous day.

The metrics can be improvised, here is a case study where the graph is performing poorly on showing a correct trend, considering the live data from the webpage:

For example on 09 June 2020, the graph shows a decline in the number of active cases and also confirmed cases: 
Comparing the change from previous day:

_On 8th June, the ratio of No. of people tested to the no. of confirmed cases is 13.05
On 9th June, the ratio of No. of people tested to the no. of confirmed cases is 12.79_ 

This is misleading for a trend because for every 12.79 people tested we see that there is 1 confirmed case found, this means the graph should go **upwards** relatively, as a trend because earlier it was 1 confirmed case for every 13.05 people tested, the `relative change` is, in fact, **greater**.

_Also, on 8th June, the ratio of no. of confirmed cases to the no. of active cases is 2.04, 
and on 9th June, the ratio of confirmed cases to the no. of active cases is 2.88._ 

Although this change is not dramatic, the minigraph shows a sharp decline in the trend of active cases.

A possible fix would be to make the data relative accordingly or change the evaluation metrics.

**Comment by shuklaayush** [comment]
In the first part, what you're essentially saying is that instead of using the daily confirmed count as the basis for the confirmed minigraph (trends), we should instead use the Test positivity rate (TPR), since, in theory, it should be a better indicator of how much the virus is spreading. 

While I agree with the intention, I'm not a fan of adding more complexity to the way any metric/graph is calculated on the website. Even with a relatively simple thing like _Active cases_, we've already had a tough time explaining what they actually represent. Any heuristic-based normalization of the charts which is difficult to interpret on face-value will just add to the confusion. 

As an example, normalizing based on total tests only makes sense for the _Confirmed_ count. For _active/recovered/deceased_, we would rather have to normalize based on either their previous values or the _Confirmed_ count at that time. This makes the calculations asymmetric, adding to the complexity again. I'll be happy to make a change if there's an elegant way to get around this.
