### ISSUE TITLE
 Adding support for localization using i18n

### ISSUE THREAD

**Issue by AdityaKhanna** [covid19india/covid19india.github.io#21]
As discussed, we need to add support for regional languages for the users to access the information. Finer details still need to be ironed out.

**Comment by jeremyphilemon** [comment]
I think having a language selector would be a much better ux flow! 

Here's a quick mockup I made to on how we can implement the language selection.
<p align="center">
<img width="422" alt="Screen Shot 2020-03-23 at 1 25 26 PM" src="https://user-images.githubusercontent.com/17938322/77307200-e574ed00-6d09-11ea-8dea-707ce8e7b2ef.png">
</p>

**Comment by sangamesh1439** [comment]
Do we really need localisation support ?

**Comment by sauravpratihar** [comment]
Instead of all region languages I think we have to include Hindi as for now. 
Suggestion?

**Comment by AdityaKhanna** [comment]
@sangamesh1439 it's been marked as `low priority` - that should answer your question about whether it's needed. 

@sauravpratihar - the framework to add support for different languages stays the same - once it has been done for any one other language, it can be easily scaled for other languages. We can start with Hindi as the first language. But other languages would need to follow up soon

**Comment by harshzalavadiya** [comment]
Can I take this issue?

I have created a very quick demo for showing translation setup using `react-i18next` 
https://covid19india-react-three.now.sh/

* as of now it's only translating single key I'll add other keys and submit PR

also is this project using any sort of formatter/linter because I have seen many unused imports, will it be okay if I cleanup imports and add prettier?

**Update**: It's done and demo at https://covid19india-react-three.now.sh/

**Comment by Nijanthane** [comment]
Regionalization would be a good thing to have!

**Comment by jeremyphilemon** [comment]
@harshzalavadiya mentioned you in #432

**Comment by rohandebsarkar** [comment]
In language selector bengali is written as "বাঙালি" where as the original spelling is "বাংলা", I would request you to change it.
