### ISSUE TITLE
Main Table displaying all states data.

### ISSUE THREAD

**Issue by Deephacks619** [covid19india/covid19india.github.io#2100]
**Is your feature request related to a problem? Please describe.**
Yes,My feature related to problem is on main table which displaying all states covid19 data.I have so many problems regarding this. 

**Describe the solution you'd like**
Firstly, You know the table must be sorted according to highest number of cases among states, by this we can easily determine the highest number of cases in country with respective of states.
Secondly, the total cases which are confirmed, active,recovered,deceased should shown at top of table, by this people can easily understand the daily increasing,recovering cases in india .

**Comment by shuklaayush** [comment]
The table can be sorted whichever way you want. Just click on the table headers. 

As for keeping the Total row at the top, what's the point since the total numbers are already just above the table? And that too, in big font.
![image](https://user-images.githubusercontent.com/27727946/84124283-a3ca2780-aa58-11ea-9c93-e0f0af6464bb.png)
