### ISSUE TITLE
Count for Mumbai cases

### ISSUE THREAD

**Issue by brunettebungirl** [covid19india/covid19india.github.io#2193]
Hello,
The following query is for June 27, 2020, numbers for Mumbai.

![119174F0-8661-4F8C-8C74-860E5AC494CA](https://user-images.githubusercontent.com/63142557/85941987-0457d080-b944-11ea-8264-b3d156a486fc.jpeg)
![74F5545F-37FD-4598-9FCE-FF724F90D4AE](https://user-images.githubusercontent.com/63142557/85941992-07eb5780-b944-11ea-9a8e-a938db003333.png)

As per Mumbai BMC’s tweet, the number of new positive cases was 1460 and the recoveries were 2587. However on the portal there seems to be a discrepancy in numbers. Could you please cross check the same?

**Comment by shuklaayush** [comment]
Hey! We follow the MH state bulletin for Mumbai numbers, and not BMC directly. Our total counts seem to tally with MH government [website](https://arogya.maharashtra.gov.in/1175/Novel--Corona-Virus). The discrepancy could be due to a number of reasons (like backlogs being added to the state data etc.). It's anyone's guess. 

/cc @bee-rickey

**Comment by bee-rickey** [comment]
@brunettebungirl Hi, we do not follow BMC updates. We follow state bulletins. Please refer to state bulletins and let us know if you see an issue with the data we've put out for the respective days. Will be closing this issue. Please tag me if you have any specific inputs.
