### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by CodeMyGame** [covid19india/covid19india.github.io#2227]
(https://user-images.githubusercontent.com/14895638/86869686-a0c46480-c0f4-11ea-832b-e9cbab318161.png)

Check above screenshot

Issue :language menu and date wise sorting UI merged

- OS: iOS
- Browser : safari
- Device : iphone 7

**Comment by shreeshampandey** [comment]
> (https://user-images.githubusercontent.com/14895638/86869686-a0c46480-c0f4-11ea-832b-e9cbab318161.png)
> 
> Check above screenshot
> 
> Issue :language menu and date wise sorting UI merged
> 
>     * OS: iOS
> 
>     * Browser : safari
> 
>     * Device : iphone 7
The webpage wrapping seems to have been taken a front and back wrap issue but it seems to be the problem of your browser that somehow prevents the resizing of sections of site browser window. I checked in various versions of Safari(esp. of iOS 11 and 12 of iPhone 7, 8 and X Pro) but all seems to be okay there.
![wrpios11ip7cvid19ind](https://user-images.githubusercontent.com/66004487/86906788-ad1ae280-c131-11ea-94f1-3a28506af524.png)

**Comment by anand-kay** [comment]
This issue exists on my Android Google Chrome also. To replicate, click the icon to show the past date picker, then click language button.

Maybe it's a z-index issue. I haven't looked at the code for this part though, and I'm not sure how it's built.

**Comment by shreeshampandey** [comment]
Oh...now I got it! The position of the 'actions timeline' remains as it is even when you click on (or not, looking as if it is permanently set there '') ) language selection button. That portion of dates-timeline remains in its place whatsoever. 
I first thought it is flex-box issue and was somewhat right. The thing is that is, it is a simple layout error due to wrong value assigned to position in 'header timeline'. The assigned value is set as 'absolute' but it is rather 'static'.
Assigning the value of position in header timeline as 'static' solves this issue. 
Thanks for letting this issue be known!
@jeremyphilemon 
![Screenshot from 2020-07-10 09:34:51](https://user-images.githubusercontent.com/66004487/87115927-3a754880-c292-11ea-8675-55e1f40588fd.png)
![Screenshot_2020-07-10 Coronavirus in India Latest Map and Case Count](https://user-images.githubusercontent.com/66004487/87115977-5bd63480-c292-11ea-9a64-e992d2bf9b81.png)
![Screenshot from 2020-07-10 09:34:05](https://user-images.githubusercontent.com/66004487/87116026-77413f80-c292-11ea-9623-d854ea384e58.png)
![Screenshot_2020-07-10 Coronavirus in India Latest Map and Case Count(1)](https://user-images.githubusercontent.com/66004487/87116032-7b6d5d00-c292-11ea-9c10-582f130c77d4.png)

**Comment by shuklaayush** [comment]
Duplicates #2225
