### ISSUE TITLE
how you get the district wise tested data?

### ISSUE THREAD

**Issue by debrajhyper** [covid19india/covid19india.github.io#2366]
tell me in which API I would find the State-District-Wise tested data.

**Comment by shuklaayush** [comment]
If you're brave enough, then you can try [`district_testing.csv`](http://api.covid19india.org/csv/latest/district_testing.csv). Otherwise, use [`data.json`](https://api.covid19india.org/v4/data.json). It should have testing data for districts under the `total:tested` key.

Keep in mind that we only collect testing data for a subset of districts, and in some cases, this data might also be outdated.
