### ISSUE TITLE
No Districts in Delhi [Question]

### ISSUE THREAD

**Issue by ShadabFaiz** [covid19india/covid19india.github.io#2378]
This is neither a bug report nor a feature request. It is a question.
Earlier the map used to have the districts of Delhi, but now, it does not have. I have looked into the delhi.json file and there is only 1 district called Delhi. Is there any reason for removing other districts?

**Comment by shuklaayush** [comment]
Yes, since the Delhi health bulletin doesn't contain district-wise split of the data and never will, it made no sense to keep the district map. It just created more confusion with us adding an 'Unknown' district to compensate for that. If you want the district map of Delhi for any other purpose, you can get it by going through the Git history.
