### ISSUE TITLE
Lots of Pull Requests are left to be reviewed and merged.

### ISSUE THREAD

**Issue by Rajanpandey** [covid19india/covid19india.github.io#248]
Problems arising due to PRs being unchecked:
1. We are getting duplicate issues for old issues whose PRs are already created but not merged.
2. Someone else is creating a new PR for the duplicate issue even though one PR is already created for the same issue which was raised originally hence redundant work is being done.
3. Merge conflicts are arising every day in the old PRs which is a big pain.
I created 4 PRs till now and none of them are merged yet. Some of them are reviewed and approved by some contributors yet not merged.
I understand that the @jeremyphilemon is occupied with lots of work at hand. Can we have more reviewers who can check the PRs and merge them?

**Comment by KrishnaPravin** [comment]
#161

**Comment by KrishnaPravin** [comment]
#161

**Comment by KrishnaPravin** [comment]
@JunaidBabu  @jeremyphilemon  @sudevschiz
- Please add what each label 🏷means either in root README or in CONTRIBUTING. So that contributors can pick the right issue ✅to work on.
- Please mention UI enhancements that are not relevant to the core purpose  💝of the site will not be merged. So that contributors would spend their time more on fixing the existing issues 🔍rather than applying their creativity 🎨in CSS.
