### ISSUE TITLE
Fix the range for the # deaths reported per day

### ISSUE THREAD

**Issue by prabhuvashwin** [covid19india/covid19india.github.io#2502]
**Describe the bug**
Currently, the number of deaths reported per day has a range from -2L to 8L, and since the # of deaths per day is ~3K, this graph is always a straight line. Fix the range to represent the data -> -2K to 10K would be accurate.

**To Reproduce**
Please see the screenshot attached below

**Expected behavior**
The # of deaths graph should represent the scale of the data, and should show the increase and decrease in reported deaths

**Screenshots**
<img width="890" alt="Screen Shot 2021-06-15 at 23 59 07" src="https://user-images.githubusercontent.com/22184820/122173015-2a68d000-ce36-11eb-8e9e-139bc25e5bdc.png">

**Comment by ujjwalpuri29** [comment]
**Workaround** 
If you uncheck the uniform button above the graphs, all graphs will have their own scale and this will not be a straight line 

**Recommendation**
Other graphs like tested and vaccination have their own scale since their data is different. Similarly we can have a custom scale for this. Although I do realise that uniform scale is to show that number of deaths is wayyyyy less than confirmed cases so as to not instill fear I guess but having a straight line doesn't really help the cause
