### ISSUE TITLE
After changing language and then coming back to english, the search placeholder displays weird strings

### ISSUE THREAD

**Issue by sheeerio** [covid19india/covid19india.github.io#2507]
![Screenshot 2021-06-27 at 7 06 00 PM](https://user-images.githubusercontent.com/56512776/123546563-b81fb600-d77a-11eb-9bbd-c50370b3cb46.png)

**Comment by sbhrwlr** [comment]
I think this is happening due to use of useCallback hook whenever we change language it is starting a new function without terminating the previous callback instance and mixing the city region names like in your example it is mixing Karnataka and Alappuzha. And if we create terminating point it will terminate all the instances of useCallback function. I guess this is the reason correct me if I am wrong.

**Comment by shuklaayush** [comment]
Duplicates #2322
