### ISSUE TITLE
District names overflowing to the back button

### ISSUE THREAD

**Issue by shuklaayush** [covid19india/covid19india.github.io#304]
On mobile, long district names overflow and appear over the back button in expanded view.

![image](https://user-images.githubusercontent.com/27727946/77832046-1ebdba80-7159-11ea-9a1c-26c138d55785.png)

**Comment by techhysahil** [comment]
Change style to following:
.MapExplorer .meta h2 {
    margin: 0;
    color: #e23028;
    word-wrap: break-word;
    font-weight: 900;
    width: calc(100% - 80px);
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;	
}

**Comment by Nitin96Bisht** [comment]
@shuklaayush Kindly also provide expected behavior so that we can start working on this.

I have tried and it looks like:
![image](https://user-images.githubusercontent.com/23516674/77843254-ff567a00-71b8-11ea-87ef-1b3c0093e4a7.png)

Although for smart districts it looks like:
![image](https://user-images.githubusercontent.com/23516674/77843279-27de7400-71b9-11ea-98ed-c75282933534.png)

Kindly check and tell expected behaviors. I will change it.

**Comment by jeremyphilemon** [comment]
@Nitin96Bisht that looks good! Assign yourself and take up the issue :)

**Comment by jeremyphilemon** [comment]
This has been fixed!

**Comment by Nitin96Bisht** [comment]
@jeremyphilemon Have you done this? I can see it has not been fixed it.
