### ISSUE TITLE
Display Active case %, Mortality %, and Recovery %

### ISSUE THREAD

**Issue by sandeephegde16** [covid19india/covid19india.github.io#447]
**Is your feature request related to a problem? Please describe.**
Now that we have lots of data in hand, its good to show mortality rate and also recovery rate by country, i.e., India, by each state wise and district wise.

**Describe the solution you'd like**
Active Case % = Total Population of country or State / Active case of country or state
Mortality Rate = Total active case / Total deceased case
Recovery Rate = Total active case / Total recovered cases

**Comment by sudevschiz** [comment]
This could be part of the detailed state-view that we have planned. @jeremyphilemon

**Comment by sudeepnokia** [comment]
For calculating mortality rate correctly, we should be using deceased count as of today, and the number of cases as of 7 days ago:
Mortality rate = 100*(deceased as of now)/(cases as of 7 days ago)

This is because people who were detected as positive a week ago will be the ones who will die now
In other words, the mortality curve lags the detection curve by a week

References:
https://www.youtube.com/watch?v=qOF5a3I7puQ&t=22m54s  (from around 22m to 30m)
https://www.thelancet.com/action/showPdf?pii=S1473-3099%2820%2930195-X

**Comment by jeremyphilemon** [comment]
Closed in favor of #1496
