### ISSUE TITLE
[Question] Roadmap?

### ISSUE THREAD

**Issue by ShadabFaiz** [covid19india/covid19india.github.io#468]
Do you guys have any roadmap for this project? What features are being worked on / will be worked on in the future, is there any specific skill that you would like a person to get in touch with.

**Comment by sandeephegde16** [comment]
It would be better to select few suggested enhancements, prioritize it and update in Readme.md (Atleast) So that people will have an idea where we are progressing.

**Comment by vandanachandola** [comment]
I agree, I am looking for issues to work on but everything "available" seems to be already in progress and it's a bit difficult to find something.

**Comment by jeremyphilemon** [comment]
Thanks for addressing this, I think this is a good idea! I'll open a roadmap sometime today so that it can help people understand what's being focused on right now!

**Comment by debasishdebs** [comment]
Have you guys thought about Graphical way to identify Clusters/Hotspots? Some sort of Graph analytics + Viz? 
I know you guys used to have a Graph representation but it seems to be removed now. I've worked with Graph databases and Analytics extensively and here is what I propose:

1. For every patient detected, we know the state, city, and maybe even the region they belong to like neighborhood (Atleast for big cities with max cases) based on stated releasing information.
2. We know travel history of lot of patients, atleast I suspect more than 50%. How about we track that? From international source to domestic route to point of detection? I know Telangana, AP, Odisha govt releases few of those. Maybe other states do as well.
3. Now more and more states are going to make the containment/quarantine zones public. Maharastra did it, Odisha did it, UP is going to do it and other will follow suit. We can then map the patients to those zones for users to easily identify hotzones near them which they can avoid.
4. Once we have above information on Graph, or collect those data, we can then easily identify hotspots independent of Govt, identify the trend of growth of decline in each state, then we can also ask permission to collect location from our users, and send out custom notifications w.r.t stay safe for our users who are near to Hostpots, thus helping community in wider way.
5. Also, add to that, on longer run, since this will be lasting more than just few weeks, we can incorporate various techniques to encourage people to stay at home, by suggesting them options like nearby groccery stores, essential shops, medicine shops etc. (this might seem far stretched).

Also, is state wise testing information made public? Some states do it, but do all states? We can also incorporate that as well.

Let me know what you guys think about above.

**Comment by sudevschiz** [comment]
@debasishdebs 
1. This information has become more and more sparse. We only get District-level information now
2. No. If that information is available, we are capturing it in the comments. If the information is available, this api by @NirantK can extract the information : https://github.com/covid19india/api/issues/6

3. Capturing the quarantine zone is a work in progress. 
4. I am failing to understand how any graph db will add benefit as we are getting information in bulk more and more. 
5. Yep, if technology can help in that, would love to hear more about it.

Please do reopen the issue if you have PoC in mind. You can share your plan and what data will have to be collected. 

Sorry for the delay in revert.

**Comment by jeremyphilemon** [comment]
Also roadmap has just been put up! https://github.com/covid19india/covid19india-react/projects/1?fullscreen=true
