### ISSUE TITLE
Default selection of graphs should not be scale uniformly

### ISSUE THREAD

**Issue by Nikhiljoseph31** [covid19india/covid19india.github.io#494]
The scale uniformly toggle is defaulted to yes, the default should be no since the data between deaths or recovered and confirmed cases will not be in the same range

**Comment by jeremyphilemon** [comment]
Hey, thanks for filing the issue.

The decision to keep it toggled on default was intentional by design. When the graphs are first shown, it is important to have the axis across them uniform in order to compare the magnitude between them easily. When they're not uniform, all the graphs will hit the ceiling in their own scales and show a distorted representation of the numbers.

Hence the decision :)
