### ISSUE TITLE
Legend in the map and the data in the map seems different

### ISSUE THREAD

**Issue by steffyjohn** [covid19india/covid19india.github.io#57]
![COVID-19 Tracker   India -legend](https://user-images.githubusercontent.com/45359124/77419124-e717e100-6ded-11ea-9f0b-28fcf8d5e004.png)

The legend used  in the map for showing the  color  for corresponding data(Kerala) seems different as seen in the screenshot

**Comment by jeremyphilemon** [comment]
@shuklaayush hey can you look at this?

**Comment by sudevschiz** [comment]
@steffyjohn Seems fine for me. Can you elaborate?

**Comment by shuklaayush** [comment]
I think the issue is that the state colours are assigned directly from a continuous colour space, while the legend is a sampled version of the colour space. Hence, there's the possibility of a mismatch. We can either switch to a continuous legend, or assign colours from the sampled colour space. Any thoughts?

**Comment by jeremyphilemon** [comment]
@shuklaayush You're right, the colors on the map are based on a scaling factor, I think it'd be appropriate if the legend used the same too! 

Let me know if you'd like me to assign you for this fix!

**Comment by shuklaayush** [comment]
@jeremyphilemon The legend is already scaled as well. I think the issue is rather that the legend is a fixed set of 6 coloured blocks instead of a continuous scale. Right now, the fixed colour is the colour of the lower bound of the range. 

What do you think about this?

![Screenshot from 2020-03-25 14-26-34](https://user-images.githubusercontent.com/27727946/77518980-afb83b80-6ea4-11ea-9e40-7cf4057b80d1.png)

**Comment by jeremyphilemon** [comment]
Patched #51
