### ISSUE TITLE
Set SCALE UNIFORMLY to false by Default

### ISSUE THREAD

**Issue by ghost** [covid19india/covid19india.github.io#59]
My personal id is: https://github.com/vinay13091993
I have a suggestion.
Currently SCALE UNIFORMLY checkbox is set to **true** by default. Please make it **false** just for the sake of better user experience.

![image](https://user-images.githubusercontent.com/50363928/77420275-bdf85000-6def-11ea-8bd2-525b7277a9b1.png)

**Comment by shuklaayush** [comment]
Maybe change the text to 'Uniform Scaling' as well.

**Comment by JunaidBabu** [comment]
design choice! won't fix.

different scales will give the wrong idea to users.

**Comment by shubhamg0406** [comment]
> design choice! won't fix.
> 
> different scales will give the wrong idea to users.

All of these charts represent different numbers, what we currently have gives a wrong idea, not the other way around. 

If the numbers mean different things, they should be presented differently. Hence not keeping it uniform provides a better experience.

Edit: Also, since all of these numbers are rising in an exponential manner, only the first graph gives this impression while the other ones look non-exponential. This because we are comparing apples and oranges in the same scale.

**Comment by shuklaayush** [comment]
I agree with @thanoskaka, but for different reasons. If we wanted uniform scaling, we could have plotted everything on the same graph. Separating them into different graphs, but keeping the scales uniform by default seems like a perfunctory approach.
