### ISSUE TITLE
Previous day data is not updated in graph eventually.

### ISSUE THREAD

**Issue by Jasmin2895** [covid19india/covid19india.github.io#657]
When I check the data at midnight the daily count is set to 0 and the graph is not updated. It shows data until the day before yesterday. Also, the logarithmic view is not working.
<img width="555" alt="Screenshot 2020-04-05 at 1 07 18 AM" src="https://user-images.githubusercontent.com/8161593/78459877-da429980-76d9-11ea-9430-8bccde8d436f.png">
I checked this data around 1 AM.

**Comment by jeremyphilemon** [comment]
@Jasmin2895 thanks for filing the issue! 

About the data, the timeseries graphs are filled only till T-minus one day, hence if today is April 2, the data for timeseries is only available till April 1 since the day is not over yet. With that said, the graphs are not reset at 12am IST, it takes some time for the data team to sanitize and verify the data for said day before releasing its data, hence the day :)

Regarding logarithm, it is intentionally disabled for dailys. Correct me if I'm wrong, but don't logarithm graphs give meaningful information only for continuous data and not for discrete data?

**Comment by Jasmin2895** [comment]
@jeremyphilemon yes, the logarithmic graph shouldn't be used to show data on a daily basis the best graph is the bar graph or the stacked bar graph which is already used! 😄

**Comment by jeremyphilemon** [comment]
Haha glad that got resolved :)
