### ISSUE TITLE
Shows wrong data

### ISSUE THREAD

**Issue by kishorecs** [covid19india/covid19india.github.io#670]
![Screenshot_2020-04-05-11-45-15-757_com android chrome](https://user-images.githubusercontent.com/19317893/78468273-d479a200-7733-11ea-92c0-a49f34260f8c.jpg)

Check the increase count in Kurnool and AP

**Comment by AbhishekRaj-droid** [comment]
Hey, I know you are trying to suggest the fault, but you should wait some time before logging issue, because they are updating it, and it will be very difficult to filter out the critical issue if we log such issue frequently.

I am just suggesting you to collaborate with Telegram for such issue, here we should focus more on making the website more efficient, such as clustering feature is pretty much slow, how to make that more efficient. 

(![image](https://user-images.githubusercontent.com/30465215/78468585-f1fc3b00-7736-11ea-8388-170704508982.png))
