### ISSUE TITLE
Make updates interactive

### ISSUE THREAD

**Issue by BhaveshSGupta** [covid19india/covid19india.github.io#787]
**Is your feature request related to a problem? Please describe.**
Currently in updates section we are showing updates sources of data. But it non interactive normally updates are clickable section a user see individual updates

**Describe the solution you'd like**
We can add link to original source so that if any one needs to check source for this information they can see that.

**Comment by BhaveshSGupta** [comment]
I can work on this, if any one else cannot pick one!

**Comment by jeremyphilemon** [comment]
@BhaveshSGupta this sounds good, what strategy would you use to achieve this?

**Comment by BhaveshSGupta** [comment]
@jeremyphilemon, We need to add source URL into https://api.covid19india.org/updatelog/log.json, afaik this api is used to manage update. All data is coming from google doc where sources are mentioned. So we can't add sources from there?

**Comment by jeremyphilemon** [comment]
@JunaidBabu do you think is still possible?

**Comment by JunaidBabu** [comment]
> 
> 
> @jeremyphilemon, We need to add source URL into https://api.covid19india.org/updatelog/log.json, afaik this api is used to manage update. All data is coming from google doc where sources are mentioned. So we can't add sources from there?

updates log was a temporary thing created to notify (internally) volunteers about the data being published to the api and website. It won't make much sense to add sources because that log.json is a concise version of data updates since the last epoch of api actions. And it only contains the last 50 updates.

The same information is also published in the telegram channel https://t.me/covid19indiaorg_updates
