### ISSUE TITLE
There is a random character in city dropdown list

### ISSUE THREAD

**Issue by ninjakx** [covid19india/covid19india.github.io#862]
**Describe the bug**

**To Reproduce**

1. Go to 'essential page'
2. Click on 'Andhra Pradesh' from 'choose state' 
3. There is this F in the city dropdown option.

**Screenshots**
![Screenshot from 2020-04-09 22-43-05](https://user-images.githubusercontent.com/29797787/78922353-054f3380-7ab4-11ea-992d-b2a04718a8c7.png)

**Comment by Nitin96Bisht** [comment]
@ninjakx issue is with the API. Kindly report an issue https://github.com/covid19india/api

**Comment by rominj** [comment]
https://github.com/covid19india/api/blob/master/resources/resources.json

"category": "Fundraisers",
"city": "F",
"contact": "http://www.irdwsi.in",

This file has an F as District name for Andhra Pradesh. It should be changed to Visakhapatnam. because The Integrated Rural Development of Weaker Sections in India (WIDA) is located at Visakhapatnam and comes under Fund Raisers.

**Comment by bee-rickey** [comment]
Communicated to the relevant team. Closing this.
