### ISSUE TITLE
ESSENTIAL result table doesn't scale properly on small screen

### ISSUE THREAD

**Issue by dpnkrpl** [covid19india/covid19india.github.io#884]
The table containing the search results under the ESSENTIAL page doesn't scale properly on mobile devices.
![Screenshot_2020-04-10-08-30-24-890_com android chrome](https://user-images.githubusercontent.com/27947066/78958546-f7c29980-7b05-11ea-9519-49b7080ef9a3.jpg)

**Comment by RamaKrishnaKunda** [comment]
I see that the issue is only coming for Chandigarh and Jharkhand.

**Comment by dpnkrpl** [comment]
> I see that the issue is only coming for Chandigarh and Jharkhand.

Yeah that's right, I checked too. Probably the long medical center names are the reason.

**Comment by shubhamjain2998** [comment]
As I can see from source code, this issue can be fixed with few lines of CSS, I request you to assign this issue to me. @deep5050 @RamaKrishnaKunda @sudevschiz 
See the below working Screenshot.
![Screenshot from 2020-04-13 14-59-37](https://user-images.githubusercontent.com/30628775/79110156-6e29fa80-7d97-11ea-8e1c-7fb4257e7e85.png)
![Screenshot from 2020-04-13 14-59-17](https://user-images.githubusercontent.com/30628775/79110160-6f5b2780-7d97-11ea-97cf-b0ab392d88d0.png)
