### ISSUE TITLE
Display percentage of number of positive cases per number of tests conducted in a day.

### ISSUE THREAD

**Issue by Parag-Yadav-09** [covid19india/covid19india.github.io#905]
In the coming days, the positive test count is going to get increased only as government is increasing the number of test which is being conducted in a day to check the community spread. And this will be the ideal graph to keep a check at community level.

There should be a graph on main screen which tells the percentage of positive cases per number of tests conducted in a day.

Rest all the graphs will show steep curve only, but I hope this one shows gradually decreasing curve in the coming days.

If we have the data of number of test which is being conducted in a day, we can have this graph very easily. It will be most useful graph to keep a check on the community level.

**Comment by bee-rickey** [comment]
Can be part of deep dive.

**Comment by vedadeepta** [comment]
@Maverick-09 are you working on this ? if not can maintainers please assign me this issue.

**Comment by Parag-Yadav-09** [comment]
@vedadeepta I would like to work on it, but I'm just an automation tester nd have less knowledge in this department. But I'm eager to learn more. If this ticket get assigned to you, Can I ping you on hangout? I have got your email id from profile, you could just let me know how u did it.

**Comment by vedadeepta** [comment]
Hey I'm no expert myself. From skimming the deep dive codebase it seems like they use `react-chartjs-2` library to plot graphs. Seems the api is reasonably simple(you can read docs at their GitHub repo), although some trial/error might be required since i haven't used the lib before. you can give it a try yourself. Look here for reference: https://github.com/covid19india/covid19india-react/blob/master/src/components/Charts/totalconfirmedchart.js

also feel free to ping. No issues there. If you want to work on this one ask the mods to get it assigned to you and i can help you if you have issues. @Maverick-09

**Comment by faisal3389** [comment]
I can work on this if this has not been picked yet.

**Comment by kunalpgithub** [comment]
@faisal3389  have you started on it.
I don't know from where to get data for this. Is there any API build for this?

**Comment by vedadeepta** [comment]
@kunalpgithub the data is available from this [api](https://api.covid19india.org/data.json). `totalindividualstested` & `totalpositivecases` is available in the `tested` array along with timestamps.

**Comment by AnshulAg03** [comment]
@kunalpgithub @faisal3389 I can work on this if you guys have not started it.

**Comment by jeremyphilemon** [comment]
Closing in favor of #1496
