### ISSUE TITLE
Poor Seo for the website

### ISSUE THREAD

**Issue by SaiTeja69** [covid19india/covid19india.github.io#931]
The website is great but the seo for this page is weak.

**Comment by sudevschiz** [comment]
Please do let us know the suggestions you have.

**Comment by SaiTeja69** [comment]
On page seo , add keywords related to corona such as covid , corona ,
covid-india , word which an Indian user might search to look up for the
meter would improve the page ranking.

**Comment by sudevschiz** [comment]
We had added some meta tags to the page. Currently we don't have any intentional plans make the website more popular for the sake of making it popular. 

However, will keep this mind. Organically, when we have more content in graphs section, this problem would solve on its own. 

Closing this for now.
